usernameAmazon: marior6@uci.edu
passwordAmazon: 3$b0QZjsB0TuPaDe8yv#nZxn$RX^m7
usernameEbay: marirodrigue_564
passwordEbay: awB@#4E!cGLJXEoO%3YoiT8fr
usernameCraiglist: marior6@uci.edu
passwordCraiglist: 3%eF05r026ZwX5o5^^Oe