# Put your credentials here. Just un-comment and type username and password for the sites you want

# usernameAmazon : 
# passwordAmazon : 
# usernameEbay : 
# passwordEbay : 
# usernameCraiglist : 
# passwordCraiglist :
